angular.module("app").factory "AllNootsService", ($q, NootBuilder) ->

  @noots = [
    NootBuilder.noot_from_name("1-3-Dimethylamylamine"),
    NootBuilder.noot_from_name("5-HTP"),
    NootBuilder.noot_from_name("Adrifinil"),
    NootBuilder.noot_from_name("Agmatine"),
    NootBuilder.noot_from_name("ALCAR"),
    NootBuilder.noot_from_name("Alpha-GPC"),
    NootBuilder.noot_from_name("Alpha-Lipoic Acid"),
    NootBuilder.noot_from_name("Aniracetam"),
    NootBuilder.noot_from_name("Asparagus Racemosus"),
    NootBuilder.noot_from_name("Bacopa Monnieri"),
    NootBuilder.noot_from_name("Berberine"),
    NootBuilder.noot_from_name("Blueberry"),
    NootBuilder.noot_from_name("Boswellia Serrata"),
    NootBuilder.noot_from_name("Bulbine Natalensis"),
    NootBuilder.noot_from_name("CDP-choline (Citicholine)"),
    NootBuilder.noot_from_name("Caffeine"),
    NootBuilder.noot_from_name("Centrophenoxine (Meclofenoxate)"),
    NootBuilder.noot_from_name("Clenbuterol"),
    NootBuilder.noot_from_name("Clitoria Ternatea"),
    NootBuilder.noot_from_name("Coluracetam"),
    NootBuilder.noot_from_name("Convolvulus pluricaulis"),
    NootBuilder.noot_from_name("Creatine"),
    NootBuilder.noot_from_name("D-Aspartic Acid"),
    NootBuilder.noot_from_name("D-Serine"),
    NootBuilder.noot_from_name("Dark Therapy"),
    NootBuilder.noot_from_name("Dehydroepiandrosterone"),
    NootBuilder.noot_from_name("Dimocarpus Longan"),
    NootBuilder.noot_from_name("Emblica officinalis"),
    NootBuilder.noot_from_name("Eschscholzia Californica"),
    NootBuilder.noot_from_name("Evolvulus alsinoides"),
    NootBuilder.noot_from_name("Fenugreek"),
    NootBuilder.noot_from_name("Fish Oil"),
    NootBuilder.noot_from_name("GABA"),
    NootBuilder.noot_from_name("Ginger"),
    NootBuilder.noot_from_name("Glycine"),
    NootBuilder.noot_from_name("Grape Seed Extract"),
    NootBuilder.noot_from_name("Green Tea Catechins"),
    NootBuilder.noot_from_name("Ginko biloba"),
    NootBuilder.noot_from_name("Hordenine"),
    NootBuilder.noot_from_name("Huperzine-A"),
    NootBuilder.noot_from_name("Idebenone"),
    NootBuilder.noot_from_name("Krill Oil"),
    NootBuilder.noot_from_name("L-Carnitine"),
    NootBuilder.noot_from_name("L-DOPA"),
    NootBuilder.noot_from_name("L-Tyrosine"),
    NootBuilder.noot_from_name("Licorice"),
    NootBuilder.noot_from_name("Light Therapy"),
    NootBuilder.noot_from_name("Magnolia Officinalis"),
    NootBuilder.noot_from_name("Marijuana"),
    NootBuilder.noot_from_name("Melissa officinalis"),
    NootBuilder.noot_from_name("Modafinil")
    NootBuilder.noot_from_name("Modafinil"),
    NootBuilder.noot_from_name("Morus Alba"),
    NootBuilder.noot_from_name("Mucuna Pruriens"),
    NootBuilder.noot_from_name("Muira Puama"),
    NootBuilder.noot_from_name("Music"),
    NootBuilder.noot_from_name("Nardostachys jatamansi"),
    NootBuilder.noot_from_name("Nefiracetam"),
    NootBuilder.noot_from_name("Nicotine"),
    NootBuilder.noot_from_name("Noopept"),
    NootBuilder.noot_from_name("Oleoylethanolamide"),
    NootBuilder.noot_from_name("Oxiracetam"),
    NootBuilder.noot_from_name("Phenylpiracetam"),
    NootBuilder.noot_from_name("Phosphatidylserine"),
    NootBuilder.noot_from_name("Piracetam"),
    NootBuilder.noot_from_name("Pramiracetam"),
    NootBuilder.noot_from_name("Pyritinol"),
    NootBuilder.noot_from_name("Pyrroloquinoline quinone"),
    NootBuilder.noot_from_name("Resveratrol"),
    NootBuilder.noot_from_name("S-Adenosyl Methionine"),
    NootBuilder.noot_from_name("Sarcosine"),
    NootBuilder.noot_from_name("Scutellaria baicalensis"),
    NootBuilder.noot_from_name("Sulbutiamine"),
    NootBuilder.noot_from_name("Sunifiram"),
    NootBuilder.noot_from_name("Theanine"),
    NootBuilder.noot_from_name("Uridine"),
    NootBuilder.noot_from_name("Unifiram"),
    NootBuilder.noot_from_name("Vinpocetine"),
    NootBuilder.noot_from_name("Vitamin A"),
    NootBuilder.noot_from_name("Vitamin B1 (Thiamine)"),
    NootBuilder.noot_from_name("Vitamin B12"),
    NootBuilder.noot_from_name("Vitamin B2 (Riboflavin)"),
    NootBuilder.noot_from_name("Vitamin B3 (Niacin)"),
    NootBuilder.noot_from_name("Vitamin B5 (Pantothenic Aci)"),
    NootBuilder.noot_from_name("Vitamin B6 (Pyridoxine)"),
    NootBuilder.noot_from_name("Vitamin B7 (Biotin)"),
    NootBuilder.noot_from_name("Vitamin B9 (Folic Acid)"),
    NootBuilder.noot_from_name("Vitamin C"),
    NootBuilder.noot_from_name("Vitamin D"),
    NootBuilder.noot_from_name("Vitamin E"),
    NootBuilder.noot_from_name("Vitamin K"),
    NootBuilder.noot_from_name("Yamabushitake"),
    NootBuilder.noot_from_name("Yerba Mate"),
    NootBuilder.noot_from_name("Zinc"),
  ]

  return {
    noots: @noots
  }

